name: MGuns
main: io.github.qr97.mguns.MGuns
version: 0.1
commands:
  mguns:
    aliases: mg
    description: Comando principal
    usage: Use /<command> <comando>
permissions:
  mguns.use.tntcannon:
    description: Uso da arma TNTCannon
    default: op
  mguns.use.autobow:
    description: Uso da arma AutoBow
    default: op
  mguns.use.torhammer:
    description: Uso da arma TorHammer
    default: op