name: MGuns
main: io.github.qr97.mguns.MGuns
version: 0.1
commands:
  mguns:
    aliases: mg
    description: Comando principal
    usage: Use /<command> <comando>
permissions:
  mguns.tntcannon:
    description: Uso da arma TNTCannon
    default: op