name: MGuns
main: io.github.qr97.mguns.MGuns
version: 0.1
commands:
  getWeapon:
    description: Recebe a arma especificada
    usage: Use /<command> <arma>
permissions:
  mguns.tntcannon:
    description: Uso da arma TNTCannon
    default: op